/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const CategoryId = IDL.Nat;
export const ArticleInput = IDL.Record({
  'title' : IDL.Text,
  'content' : IDL.Text,
  'author' : IDL.Text,
  'imageUrl' : IDL.Opt(IDL.Text),
  'category' : CategoryId,
});
export const ArticleId = IDL.Nat;
export const Time = IDL.Int;
export const ArticleState = IDL.Record({
  'id' : ArticleId,
  'title' : IDL.Text,
  'content' : IDL.Text,
  'publishedAt' : Time,
  'author' : IDL.Text,
  'imageUrl' : IDL.Opt(IDL.Text),
  'category' : CategoryId,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const Category = IDL.Record({ 'id' : CategoryId, 'name' : IDL.Text });

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createArticle' : IDL.Func([ArticleInput], [ArticleId], []),
  'createCategory' : IDL.Func([IDL.Text], [CategoryId], []),
  'deleteArticle' : IDL.Func([ArticleId], [], []),
  'deleteCategory' : IDL.Func([CategoryId], [], []),
  'getArticle' : IDL.Func([ArticleId], [ArticleState], ['query']),
  'getArticles' : IDL.Func([], [IDL.Vec(ArticleState)], ['query']),
  'getArticlesByCategory' : IDL.Func(
      [CategoryId],
      [IDL.Vec(ArticleState)],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCategories' : IDL.Func([], [IDL.Vec(Category)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updateArticle' : IDL.Func([ArticleId, ArticleInput], [], []),
  'updateCategory' : IDL.Func([CategoryId, IDL.Text], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const CategoryId = IDL.Nat;
  const ArticleInput = IDL.Record({
    'title' : IDL.Text,
    'content' : IDL.Text,
    'author' : IDL.Text,
    'imageUrl' : IDL.Opt(IDL.Text),
    'category' : CategoryId,
  });
  const ArticleId = IDL.Nat;
  const Time = IDL.Int;
  const ArticleState = IDL.Record({
    'id' : ArticleId,
    'title' : IDL.Text,
    'content' : IDL.Text,
    'publishedAt' : Time,
    'author' : IDL.Text,
    'imageUrl' : IDL.Opt(IDL.Text),
    'category' : CategoryId,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const Category = IDL.Record({ 'id' : CategoryId, 'name' : IDL.Text });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createArticle' : IDL.Func([ArticleInput], [ArticleId], []),
    'createCategory' : IDL.Func([IDL.Text], [CategoryId], []),
    'deleteArticle' : IDL.Func([ArticleId], [], []),
    'deleteCategory' : IDL.Func([CategoryId], [], []),
    'getArticle' : IDL.Func([ArticleId], [ArticleState], ['query']),
    'getArticles' : IDL.Func([], [IDL.Vec(ArticleState)], ['query']),
    'getArticlesByCategory' : IDL.Func(
        [CategoryId],
        [IDL.Vec(ArticleState)],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCategories' : IDL.Func([], [IDL.Vec(Category)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updateArticle' : IDL.Func([ArticleId, ArticleInput], [], []),
    'updateCategory' : IDL.Func([CategoryId, IDL.Text], [], []),
  });
};

export const init = ({ IDL }) => { return []; };